### ISSUE TITLE
[FEAT] Allows ovos-utils <0.2.0

### ISSUE THREAD

**Issue by mikejgray** [NeonGeckoCom/neon-utils#506]
### Objective

Right now neon-utils can't be installed unless ovos-utils is <0.1.0. It would be nice to be able to use neon-mana-utils and other tools with newer versions of OVOS.

### Initial Implementation Requirements

Loosen ovos-utils requirement to be <0.2.0 and validate neon-utils still works properly

**Comment by NeonDaniel** [comment]
Closed by #507
